"use client";
import { useMemo } from "react";
import ReactFlow, { Background, Controls, Handle, Position, type Edge, type Node } from "reactflow";
import "reactflow/dist/style.css";
import { Badge } from "@/components/ui/badge";
import type { Priority, StudyMode, SubtopicStatus, Unit } from "@/lib/types";
import { priorityOrder } from "@/lib/utils";
type Props = { unit: Unit; subtopicStatus: Record<string, SubtopicStatus>; confidence: Record<string, number>; mode: StudyMode; showHighOnly: boolean; toppersPath: boolean; onSelectSubtopic: (id: string) => void };
const priorityStyle: Record<Priority, string> = { high: "bg-orange-100 text-orange-800", medium: "bg-amber-100 text-amber-800", low: "bg-emerald-100 text-emerald-800" };
function Root({ data }: { data: { label: string } }) { return <div className="rounded-xl bg-ink px-4 py-3 text-center text-sm font-bold text-white shadow"><Handle type="source" position={Position.Bottom} />{data.label}</div>; }
function TopicNode({ data }: { data: { label: string; priority: Priority } }) { return <div className="flow-node"><Handle type="target" position={Position.Top} /><strong className="block text-sm">{data.label}</strong><Badge className={priorityStyle[data.priority]}>{data.priority}</Badge><Handle type="source" position={Position.Bottom} /></div>; }
function SubtopicNode({ data }: { data: { label: string; priority: Priority; status: SubtopicStatus; confidence: number; attention: boolean; onClick: () => void } }) { return <button data-status={data.status} data-attention={data.attention || undefined} title={`${data.label} · ${data.priority} priority · ${data.status}${data.confidence ? ` · confidence ${data.confidence}/5` : ""}`} onClick={data.onClick} className="flow-node text-left"><Handle type="target" position={Position.Top} /><strong className="block text-sm leading-snug">{data.label}</strong><div className="mt-2 flex items-center gap-1"><Badge className={priorityStyle[data.priority]}>{data.priority}</Badge><span className="text-xs text-slate-500">{data.status.replace("_", " ")}</span>{data.confidence > 0 && <span className="ml-auto text-xs">⭐{data.confidence}</span>}</div>{data.attention && <p className="mt-2 text-[10px] font-bold uppercase tracking-wide text-rose-600">Review confidence</p>}</button>; }
const nodeTypes = { root: Root, topic: TopicNode, subtopic: SubtopicNode };
export function MindMap({ unit, subtopicStatus, confidence, mode, showHighOnly, toppersPath, onSelectSubtopic }: Props) { const { nodes, edges } = useMemo(() => { const nodes: Node[] = [{ id: "unit", type: "root", position: { x: 520, y: 0 }, data: { label: unit.title } }]; const edges: Edge[] = []; const all = unit.topics.flatMap((t) => t.subtopics); const cramComplete = all.filter((s) => s.priority !== "low").every((s) => subtopicStatus[s.id] === "done"); const topics = toppersPath ? [...unit.topics].sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]) : unit.topics; topics.forEach((topic, topicIndex) => { let subtopics = [...topic.subtopics]; if (toppersPath) subtopics.sort((a, b) => priorityOrder[a.priority] - priorityOrder[b.priority]); subtopics = subtopics.filter((sub) => { if (showHighOnly && sub.priority !== "high") return false; if (mode === "cram" && sub.priority === "low" && !cramComplete) return false; if (toppersPath && !sub.prerequisites.every((id) => subtopicStatus[id] === "done")) return false; return true; }); if (!subtopics.length) return; const x = 80 + topicIndex * 330; const topicId = `topic-${topic.id}`; nodes.push({ id: topicId, type: "topic", position: { x, y: 110 }, data: { label: topic.title, priority: topic.priority } }); edges.push({ id: `unit-${topic.id}`, source: "unit", target: topicId, animated: topic.priority === "high" }); subtopics.forEach((sub, i) => { const status = subtopicStatus[sub.id] || "not_started"; const lowConfidence = mode === "revision" && status === "done" && (confidence[sub.id] || 0) < 3; nodes.push({ id: sub.id, type: "subtopic", position: { x: x + i * 10, y: 230 + i * 112 }, data: { label: sub.title, priority: sub.priority, status, confidence: confidence[sub.id] || 0, attention: lowConfidence, onClick: () => onSelectSubtopic(sub.id) } }); edges.push({ id: `${topic.id}-${sub.id}`, source: topicId, target: sub.id }); }); }); return { nodes, edges }; }, [unit, subtopicStatus, confidence, mode, showHighOnly, toppersPath, onSelectSubtopic]); return <div className="h-[620px] overflow-hidden rounded-xl border bg-slate-50"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} fitView minZoom={0.2}><Background gap={18} size={1} /><Controls /></ReactFlow></div>; }
